# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1505693ee07e1791bf999cad34278d414dcb5a73519821e996777904989bfee2b9175bb7ce455630699941e251025869701e66181e9c2ad7c10434e2daffad0d

test:
  secret_key_base: 8f3ec9b891de4d3abbb9ababab369e1eb3ff3d5b627935aabed0bf027fc8311a96b4ca08468c3a73129f44b0a8b0c57c781803408761082eb62bba67cbea597e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
